---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170713214604"
generator:
  name: "NewRugProject"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.32.1"
  parameters:
    - "version": "0.1.0"
    - "owner": "atomist"
    - "description": "Rugs for mananging applications on CloudFoundry"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170713214604"
editor:
  name: "AddTypeScriptCommandHandler"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.32.1"
  parameters:
    - "handlerName": "ScaleApplication"
    - "intent": "scale cf app"
    - "description": "Scale a CloudFoundry Application"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-m.5"
editor:
  name: "AddTypeScriptCommandHandler"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.32.1"
  origin:
    repo: "git@github.com:atomist/cloudfoundry-rugs.git"
    branch: "master"
    sha: "c010c5a"
  parameters:
    - "handlerName": "EnableTravisDeploy"
    - "description": "enable Cloud Foundry deployments on Travis CI"
    - "intent": "enable travis cf"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-m.5"
editor:
  name: "AddTypeScriptEditor"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.32.1"
  origin:
    repo: "git@github.com:atomist/cloudfoundry-rugs.git"
    branch: "master"
    sha: "c010c5a*"
  parameters:
    - "editorName": "AddTravisDeploy"
    - "description": "add files needed to deploy to Cloud Foundry from Travis CI"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-m.7"
editor:
  name: "UpdateRug"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.34.0"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "c7ddec0ff638a1cfd019004b18917468d209883d"
    sha: "c7ddec0"

